sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'homes#top'
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'
  get 'todolists/:id' => 'todolists#show', as: 'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
end

sample_app/app/models/list.rb
class List < ApplicationRecord
  attachment :image
end

sample_app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

sample_app/app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def index
    @lists = List.all
  end
  
  def new
    @list = List.new
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to todolist_path(list.id)
  end

  def create
    list = List.new(list_params)
    list.save
    redirect_to todolist_path(list.id)
  end

  def show
    @list = List.find(params[:id])
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to todolists_path
  end

  private
  def list_params
    params.require(:list).permit(:title, :body, :image)
  end
end

sample_app/app/helpers/homes_helper.rb
module HomesHelper
end

sample_app/app/helpers/todolists_helper.rb
module TodolistsHelper
end

sample_app/app/views/homes/top.html.erb
<p>Hellllllllllllllllllo</p>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sample_app/app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@list, url: "/todolists/#{@list.id}") do |f| %>
  <%= f.label :title, "タイトル" %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body, "本文" %><br>
  <%= f.text_area :body %><br>
  <%= f.label :image, "画像" %><br>
  <%= f.attachment_field :image %><br>
  <%= f.submit "更新", disable_with: '更新ing...' %>
<% end %>

sample_app/app/views/todolists/index.html.erb
<h1>投稿一覧</h1>
<% @lists.each do |list| %>
  <%
=begin%>
 <p>タイトル</p>
  <span><%= link_to list.title, "/todolists/#{list.id}" %></span> 
<%
=end%>
  <span><%= link_to list.title, todolist_path(list) %></span>
  <%= attachment_image_tag list, :image, :fill, 100, 100, format:'jpeg' %>
<% end %>

sample_app/app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<%= form_for(@list, url: '/todolists') do |f| %>
  <%= f.label :title, "タイトル" %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body, "本文" %><br>
  <%= f.text_area :body %><br>
  <%= f.label :image, "画像" %><br>
  <%= f.attachment_field :image %><br>  
  <%= f.submit "投稿", disable_with: '投稿ing...' %>
<% end %>

sample_app/app/views/todolists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>
<h2>画像</h2>
<%= attachment_image_tag @list, :image, :fill, 100, 100, format: 'jpeg' %>

<%= link_to  "編集", edit_todolist_path(@list.id) %>
<%= link_to  "削除", destroy_todolist_path(@list.id), method: :delete, "data-comfirm" => "本当に削除しますか？" %>